name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Convert to shp and gpkg"
        run: |
          pip install -r requirements.txt
          python script/convert.py

      - name: Create GitHub release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} ./dist/*.zip -t "${{ github.ref_name }}" --generate-notes -d
